name = "sinsigma-com"
main = "index.js"
compatibility_date = "2024-04-01"

[[secrets_store_secrets]]
binding = "GEMINI_KEY"
store_id = "658de9aa2d084f2d990a0c10bd8f9c46"
secret_name = "GEMINI_KEY"
const GEMINI_API_KEY = await env.GEMINI_KEY.get();
